name: Run Selenium Tests

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        stage: "staging"
        qa: "qa"
        dev: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # If your Selenium tests use a browser in non-headless mode,
      # install the browser and set up Xvfb. If tests already run in headless mode,
      # you can omit this step.
      - name: Install Chromium and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb

      - name: Start Xvfb
        run: |
          nohup Xvfb :99 -screen 0 1920x1080x24 &
        env:
          DISPLAY: :99

      - name: Set environment variables
        run: |
          echo "BROWSER=chrome" >> $GITHUB_ENV
          echo "DRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Build and run tests
        run: mvn test -Denv=${{ inputs.environment }}

#      - name: Archive Extent Report
#        uses: actions/upload-artifact@v3
#        with:
#           name: extent-report
#           path: extent-report.html
